use nextest and emit junit

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -19,12 +19,19 @@ jobs:
 
       - run: rustup component add rustfmt
       - run: rustup component add clippy
+      - run: cargo install cargo-nextest --locked
+
+      - name: test
+        run: cargo nextest run
 
       - name: fmt
         run: cargo fmt --all -- --check
 
       - name: clippy
-        run: cargo clippy --all-targets --all-features -- -D warnings
+        run: cargo clippy --all-targets -- -D warnings
 
-      - name: test
-        run: cargo test --all -- --nocapture
+      - name: Publish Test Report
+        uses: mikepenz/action-junit-report@v3
+        if: success() || failure() # always run even if the previous step fails
+        with:
+          report_paths: '**/target/nextest/default/junit.xml'
